export const SETMENUVIEW = "SETMENUVIEW";

export const SETHOMECATEGORYMENU = "SETHOMECATEGORYMENU";
export const SETHOMECATEGORYDATA = "SETHOMECATEGORYDATA";

export const SETHOMESKIN = "SETHOMESKIN";

export const SETHOMEAGE = "SETHOMEAGE"

export const SETUSER = "SETUSER";